language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install

script:
  - php phpunit.phar -c app/phpunit.xml.dist --coverage-html web/code-coverage