services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
    rest_response:
        class: Component\Rest\RestResponse
        arguments: [@serializer]
